server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookservice
    username: root
    password: 111

logging:
  level:
    org.springframework: ERROR
    com.denar.bookservice: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: /log/app.log